language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - flake8 .
  - coverage run --source=parking -m pytest
  - pytest
services:
  - postgresql
after_success:
  - mypy .
  - coveralls
